---
# handlers file for ansible-role-deluge

- name: restart deluged
  systemd:
    state: restarted
    name: deluged.service

- name: stop deluged
  systemd:
    state: stopped
    name: deluged.service
